### ISSUE TITLE
Training the model use custom datasets

### ISSUE THREAD

**Issue by chensongloose** [w86763777/pytorch-ddpm#10]
Hello! Thanks for your great work! Excuse me, If I want to train custom datasets, how do I prepare the datasets and where do I modify the code?
Looking forward to your reply

**Comment by w86763777** [comment]
You need to write a custom pytorch dataset and update this [line](https://github.com/w86763777/pytorch-ddpm/blob/master/main.py#L97). If your image size is not 32x32, you also need to update [model.py](https://github.com/w86763777/pytorch-ddpm/blob/master/model.py) to fit your use case.

**Comment by w86763777** [comment]
Since there are no further questions, this issue is now closed.
