### ISSUE TITLE
cifar10.train.npz or cifar10_train.npz

### ISSUE THREAD

**Issue by jS5t3r** [w86763777/pytorch-ddpm#14]
First: the setup

In the Readme, it is written to download the stats `cifar10.train.npz`.
If I download the pre-trained weights [https://drive.google.com/file/d/1IhdFcdNZJRosi3XRT7-qNmiPGTuyuEXr/view?usp=sharing](drive), containing the `./logs/DDPM_CIFAR10_EPS/flagfile.txt ` there is the flag `--fid_cache=./stats/cifar10_train.npz` which is written in a different way. I guess the same file is meant. 

Second: the computation of FID is slowly because running on CPU() 
I don't get any FID because the FID calculation takes hours...

**Comment by w86763777** [comment]
You are absolutely correct. Thank you very much for reporting this issue.
The `flagfile.txt` has been corrected and the compressed file of pre-trained weights has been re-uploaded.

Closing the issue now.
