### ISSUE TITLE
Pretrained example: evaluate model and calculate FID score

### ISSUE THREAD

**Issue by jS5t3r** [w86763777/pytorch-ddpm#15]
How many samples for the FID is good? As standard is the whole cifar is used. 

The computation of FID is slowly because running on CPU(). I don't get any FID because the FID calculation takes hours... I am using an HPC and I should have a lot of CPU is there a faster way to calculate the FID?

**Comment by jS5t3r** [comment]
How long does take the FID calculation after the samples are generated?

**Comment by w86763777** [comment]
Just CPU computation is needed, and the required time usually takes less than one minute.

**Comment by jS5t3r** [comment]
OK. It gets stuck in computation in my case.

**Comment by jS5t3r** [comment]
OK. I can reproduce now your output. I set up the exact same environment. Unfortunately, I am not able to use this setup an Nvidia A100 and need to use a Titan V (12GB).

**Comment by zhangchen29** [comment]
> How long does take the FID calculation after the samples are generated?

Hi, I think you are very good, can you teach me how to run? I encountered problems during the run.

**Comment by jS5t3r** [comment]
> > How long does take the FID calculation after the samples are generated?
> 
> Hi, I think you are very good, can you teach me how to run? I encountered problems during the run.

Hi, I don't remember anymore exactly. I switched for different reasons to DDIM.
https://github.com/openai/guided-diffusion   which is a slighlty modified ddpm

**Comment by zhangchen29** [comment]
> > > How long does take the FID calculation after the samples are generated?样本生成后，FID 计算需要多长时间？
> > 
> > 
> > Hi, I think you are very good, can you teach me how to run? I encountered problems during the run.嗨，我觉得你很厉害，能教我怎么跑步吗？我在跑步过程中遇到了问题。
> 
> Hi, I don't remember anymore exactly. I switched for different reasons to DDIM.嗨，我记不清了。我出于不同的原因切换到 DDIM。 https://github.com/openai/guided-diffusion which is a slighlty modified ddpmhttps://github.com/openai/guided-diffusion 这是一个轻微的修改 ddpm

very thank you！I will try this one.
