### ISSUE TITLE
About the evaluation time on FID

### ISSUE THREAD

**Issue by zhengdharia** [w86763777/pytorch-ddpm#19]
Hi,

Thanks for the excellent work!
My question is that, to evaluate the FID score on the CIFAR10 dataset, it takes me about 17 hours to sample 50,000 images with a single 2080TI GPU. 
Is that normal? 

Many Thanks!
Best regard

**Comment by w86763777** [comment]
It is normal for the original DDPM.

**Comment by zhengdharia** [comment]
Thanks for your reply!
