### ISSUE TITLE
Question about loss

### ISSUE THREAD

**Issue by ZhouYue-Charon** [w86763777/pytorch-ddpm#7]
Hello, when you calculate the loss, you divide the output of the trainer by 1000. I would like to ask why it is divided by 1000. Shouldn't you calculate the mean of the difference of all pixels?

**Comment by w86763777** [comment]
Suppose you mean this [line](https://github.com/w86763777/pytorch-ddpm/blob/master/diffusion.py#L42) and this [line](https://github.com/w86763777/pytorch-ddpm/blob/master/main.py#L152). I follow the *simple* loss formulation in paper:
![image](https://user-images.githubusercontent.com/9026992/200720606-e854831d-9d89-4773-a6b1-c62f3b8b80c0.png)
which averages the square norm of the differences.

**Comment by ZhouYue-Charon** [comment]
> Suppose you mean this [line](https://github.com/w86763777/pytorch-ddpm/blob/master/diffusion.py#L42) and this [line](https://github.com/w86763777/pytorch-ddpm/blob/master/main.py#L152). I follow the _simple_ loss formulation in paper: ![image](https://user-images.githubusercontent.com/9026992/200720606-e854831d-9d89-4773-a6b1-c62f3b8b80c0.png) which averages the square norm of the differences.

Thanks for the reply, you are right, I got it wrong
