### ISSUE TITLE
About function: predict_xstart_from_eps

### ISSUE THREAD

**Issue by liubochong** [w86763777/pytorch-ddpm#8]
Hello, it's a nice work!
I have some questions and would like to ask you.
According to equation below: 
![image](https://user-images.githubusercontent.com/85143317/203210730-1e7cb3d8-71a8-47e0-9ac5-15837aef6fd7.png)
we can get: 
![image](https://user-images.githubusercontent.com/85143317/203212458-2c5597de-efa9-43f2-8d65-f480cd2293c3.png)
I would like to know why the implementation of this function is in this form：
![image](https://user-images.githubusercontent.com/85143317/203212732-eeeb500a-487a-4b30-b74f-14e7d5336221.png)
where the correspond parameters are defined as follow:
![image](https://user-images.githubusercontent.com/85143317/203212840-f7860280-3a46-41e5-9569-4c8f99594576.png)

**Comment by w86763777** [comment]
$$
x_0=\frac{1}{\sqrt{\bar\alpha_t}}(x_t-\sqrt{1-\bar\alpha_t\}\epsilon)=\frac{1}{\sqrt{\bar\alpha_t}}x_t-\sqrt{\frac{1-\bar\alpha_t}{\bar\alpha_t}}\epsilon=\frac{1}{\sqrt{\bar\alpha_t}}x_t-\sqrt{\frac{1}{\bar\alpha_t}-1}\epsilon
$$

**Comment by liubochong** [comment]
> x0=1α¯t(xt−1−α¯tϵ)=1α¯txt−1−α¯tα¯tϵ=1α¯txt−1α¯t−1ϵ

**Comment by liubochong** [comment]
I realised I had misread the brackets, thank you very much for your patience.
